// Code generated by protoc-gen-go. DO NOT EDIT.
// source: order/order.proto

package order

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateOrderRequest struct {
	OrderId              int64    `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Items                []*Item  `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateOrderRequest) Reset()         { *m = CreateOrderRequest{} }
func (m *CreateOrderRequest) String() string { return proto.CompactTextString(m) }
func (*CreateOrderRequest) ProtoMessage()    {}
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa47a2077d8980ed, []int{0}
}

func (m *CreateOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOrderRequest.Unmarshal(m, b)
}
func (m *CreateOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOrderRequest.Marshal(b, m, deterministic)
}
func (m *CreateOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOrderRequest.Merge(m, src)
}
func (m *CreateOrderRequest) XXX_Size() int {
	return xxx_messageInfo_CreateOrderRequest.Size(m)
}
func (m *CreateOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOrderRequest proto.InternalMessageInfo

func (m *CreateOrderRequest) GetOrderId() int64 {
	if m != nil {
		return m.OrderId
	}
	return 0
}

func (m *CreateOrderRequest) GetItems() []*Item {
	if m != nil {
		return m.Items
	}
	return nil
}

type CreateOrderResponse struct {
	OrderId              int64    `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateOrderResponse) Reset()         { *m = CreateOrderResponse{} }
func (m *CreateOrderResponse) String() string { return proto.CompactTextString(m) }
func (*CreateOrderResponse) ProtoMessage()    {}
func (*CreateOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa47a2077d8980ed, []int{1}
}

func (m *CreateOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOrderResponse.Unmarshal(m, b)
}
func (m *CreateOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOrderResponse.Marshal(b, m, deterministic)
}
func (m *CreateOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOrderResponse.Merge(m, src)
}
func (m *CreateOrderResponse) XXX_Size() int {
	return xxx_messageInfo_CreateOrderResponse.Size(m)
}
func (m *CreateOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOrderResponse proto.InternalMessageInfo

func (m *CreateOrderResponse) GetOrderId() int64 {
	if m != nil {
		return m.OrderId
	}
	return 0
}

type Item struct {
	ProductCode          string   `protobuf:"bytes,1,opt,name=product_code,json=productCode,proto3" json:"product_code,omitempty"`
	UitPrice             float32  `protobuf:"fixed32,2,opt,name=uit_price,json=uitPrice,proto3" json:"uit_price,omitempty"`
	Quantity             int32    `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}
func (*Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa47a2077d8980ed, []int{2}
}

func (m *Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item.Unmarshal(m, b)
}
func (m *Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item.Marshal(b, m, deterministic)
}
func (m *Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item.Merge(m, src)
}
func (m *Item) XXX_Size() int {
	return xxx_messageInfo_Item.Size(m)
}
func (m *Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Item proto.InternalMessageInfo

func (m *Item) GetProductCode() string {
	if m != nil {
		return m.ProductCode
	}
	return ""
}

func (m *Item) GetUitPrice() float32 {
	if m != nil {
		return m.UitPrice
	}
	return 0
}

func (m *Item) GetQuantity() int32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func init() {
	proto.RegisterType((*CreateOrderRequest)(nil), "order.CreateOrderRequest")
	proto.RegisterType((*CreateOrderResponse)(nil), "order.CreateOrderResponse")
	proto.RegisterType((*Item)(nil), "order.Item")
}

func init() { proto.RegisterFile("order/order.proto", fileDescriptor_fa47a2077d8980ed) }

var fileDescriptor_fa47a2077d8980ed = []byte{
	// 237 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0x95, 0x84, 0xb4, 0xc9, 0x85, 0x85, 0x63, 0x49, 0xc3, 0x92, 0x66, 0xca, 0x14, 0x50,
	0xf9, 0x01, 0x48, 0x74, 0xa1, 0x13, 0xc8, 0x23, 0x4b, 0xd4, 0xc6, 0x37, 0x78, 0x68, 0xed, 0xda,
	0xe7, 0x81, 0x7f, 0x8f, 0x62, 0x57, 0x48, 0x08, 0xd4, 0xc5, 0xd2, 0xe7, 0x67, 0x7d, 0x7a, 0x7e,
	0x70, 0xa7, 0xad, 0x24, 0xfb, 0x18, 0xce, 0xc1, 0x58, 0xcd, 0x1a, 0xf3, 0x00, 0x9d, 0x00, 0xdc,
	0x5a, 0xda, 0x33, 0xbd, 0xcf, 0x28, 0xe8, 0xec, 0xc9, 0x31, 0xae, 0xa0, 0x08, 0xf1, 0xa8, 0x64,
	0x9d, 0xb4, 0x49, 0x9f, 0x89, 0x65, 0xe0, 0x9d, 0xc4, 0x35, 0xe4, 0x8a, 0xe9, 0xe8, 0xea, 0xb4,
	0xcd, 0xfa, 0x6a, 0x53, 0x0d, 0x51, 0xba, 0x63, 0x3a, 0x8a, 0x98, 0x74, 0x4f, 0x70, 0xff, 0xcb,
	0xe9, 0x8c, 0x3e, 0x39, 0xba, 0x22, 0xed, 0x0e, 0x70, 0x33, 0x0b, 0x70, 0x0d, 0xb7, 0xc6, 0x6a,
	0xe9, 0x27, 0x1e, 0x27, 0x2d, 0x29, 0x3c, 0x2b, 0x45, 0x75, 0xb9, 0xdb, 0x6a, 0x49, 0xf8, 0x00,
	0xa5, 0x57, 0x3c, 0x1a, 0xab, 0x26, 0xaa, 0xd3, 0x36, 0xe9, 0x53, 0x51, 0x78, 0xc5, 0x1f, 0x33,
	0x63, 0x03, 0xc5, 0xd9, 0xef, 0x4f, 0xac, 0xf8, 0xab, 0xce, 0xda, 0xa4, 0xcf, 0xc5, 0x0f, 0x6f,
	0xde, 0x20, 0x0f, 0x7d, 0xf0, 0x05, 0x16, 0xb1, 0x1e, 0xae, 0x2e, 0xe5, 0xff, 0x2e, 0xd0, 0x34,
	0xff, 0x45, 0xf1, 0x23, 0xaf, 0xe5, 0xe7, 0x72, 0x88, 0x5b, 0x1e, 0x16, 0x61, 0xcc, 0xe7, 0xef,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xd7, 0x52, 0x4b, 0x3e, 0x61, 0x01, 0x00, 0x00,
}
